version: '3.8'

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - python-server
    environment:
      NODE_ENV: production
    volumes:
      - ./backend/node-server:/app/backend/node-server

  python-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: python-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/python-server:/app/backend/python-server

  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: react-frontend
    ports:
      - "80:80"
    depends_on:
      - node-server
    volumes:
      - ./frontend:/app/frontend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-frontend
      - node-server
